title: Lrfoster03
description:
  I'm Logan Foster, an avid maker and technologist interested in all things software and hardware!
  I graduated from Washington State University in 2024 with Bachelors of Science Degrees in Computer Science and Applied Mathematics.
author: Logan Foster
avatar: /assets/images/Personal Pic.jpeg
email: lrfoster03@gmail.com
# baseurl: "Logoas.xyz"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-environment-variables
  # - jekyll-theme-hamilton
  # - jekyll-remote-theme

paginate: 10
# remote_theme: ngzhio/jekyll-theme-hamilton
skin: daylight

# permalink: /:categories/:title/
permalink: pretty

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll-auth
# ======
jekyll_auth:
  whitelist:
    # - "^((?!draft).)*$"
    - drafts?

# Recognize Projects as a collection
collections:
  project:
    output: true
    permalink: /projects/:title/

# Jekyll
# ======
exclude:
  - scripts/
  - quartz-prototype/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: lrfoster03
  card: summary
logo: /assets/images/Personal Pic.jpeg
social:
  name: Logan Foster
  links:
    # - https://twitter.com/ngzhio
    # - https://www.facebook.com/ngzhio
    - https://github.com/Lrfoster03
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
