#!/bin/sh
# Test that all dependencies resolve, and that the thing actually fires

set -e

export GITHUB_CLIENT_ID=FOO
export GITHUB_CLIENT_SECRET=BAR
export GITHUB_ORG_NAME="balter-test-org"

script/ruby-exec bundle exec rake spec
script/ruby-exec bundle exec rubocop
script/ruby-exec bundle exec gem build jekyll-auth.gemspec
script/ruby-exec bundle exec jekyll-auth --version
